package Automation;

import Api.NbaApiClient;
import core.Game;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class AutomatedGameTracker {
    private final NbaApiClient apiClient;

    public AutomatedGameTracker(NbaApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public void runDailyReport() {
        LocalDate yesterday = LocalDate.now().minusDays(1);
        String dateStr = yesterday.format(DateTimeFormatter.ISO_LOCAL_DATE);

        System.out.println("\n" + "=".repeat(60));
        System.out.println("NBA AUTOMATED GAME TRACKER");
        System.out.println("Report Date: " + dateStr);
        System.out.println("Generated: " + LocalDate.now() + " " + java.time.LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        System.out.println("=".repeat(60) + "\n");

        // Fetch yesterday's games
        List<Game> games = apiClient.fetchGames(100, dateStr);

        if (games.isEmpty()) {
            System.out.println("No games played on " + dateStr);
            System.out.println("This is normal for off-season or休息 days.\n");
            logNoGamesDay(dateStr);
            return;
        }

        // Analyze the games
        analyzeAndReport(games, dateStr);
    }

    private void analyzeAndReport(List<Game> games, String dateStr) {
        // Create reports directory if it doesn't exist
        try {
            Files.createDirectories(Paths.get("reports"));
        } catch (IOException e) {
            System.out.println("Could not create reports directory: " + e.getMessage());
            return;
        }

        // Analysis
        int totalGames = games.size();

        // Count games by team
        Map<String, Long> teamGameCount = games.stream()
                .flatMap(g -> java.util.stream.Stream.of(g.getHomeTeamAbbr(), g.getVisitorTeamAbbr()))
                .collect(Collectors.groupingBy(team -> team, Collectors.counting()));

        // Most active teams
        String mostActiveTeam = teamGameCount.entrySet().stream()
                .max(Map.Entry.comparingByValue())
                .map(Map.Entry::getKey)
                .orElse("N/A");

        // Generate report
        try {
            String filename = "reports/game_report_" + dateStr + ".txt";
            FileWriter writer = new FileWriter(filename);

            // Report Header
            writer.write("╔" + "═".repeat(58) + "╗\n");
            writer.write("║" + center("NBA DAILY GAME REPORT", 58) + "║\n");
            writer.write("║" + center(dateStr, 58) + "║\n");
            writer.write("╚" + "═".repeat(58) + "╝\n\n");

            // Summary Statistics
            writer.write("📊 SUMMARY STATISTICS\n");
            writer.write("─".repeat(60) + "\n");
            writer.write(String.format("Total Games Played: %d\n", totalGames));
            writer.write(String.format("Teams in Action: %d\n", teamGameCount.size()));
            writer.write(String.format("Most Active Team: %s (%d game%s)\n\n",
                    mostActiveTeam,
                    teamGameCount.get(mostActiveTeam),
                    teamGameCount.get(mostActiveTeam) > 1 ? "s" : ""));

            // Game Details
            writer.write("🏀 GAME DETAILS\n");
            writer.write("─".repeat(60) + "\n");

            int gameNum = 1;
            for (Game game : games) {
                writer.write(String.format("Game %d: %s (Home) vs %s (Away)\n",
                        gameNum++,
                        game.getHomeTeamAbbr(),
                        game.getVisitorTeamAbbr()
                ));
            }

            writer.write("\n" + "─".repeat(60) + "\n");
            writer.write("Report generated by NBA Automated Game Tracker\n");
            writer.write("Timestamp: " + java.time.LocalDateTime.now().format(
                    DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) + "\n");

            writer.close();

            // Print to console
            System.out.println("✅ Report Generated Successfully!");
            System.out.println("📁 Saved to: " + filename);
            System.out.println("\n📊 Quick Stats:");
            System.out.println("   • Total Games: " + totalGames);
            System.out.println("   • Teams Active: " + teamGameCount.size());
            System.out.println("   • Most Active: " + mostActiveTeam);
            System.out.println();

            // Update tracking log
            updateTrackingLog(dateStr, totalGames);

        } catch (IOException e) {
            System.out.println("Error writing report: " + e.getMessage());
        }
    }

    private void logNoGamesDay(String dateStr) {
        try {
            Files.createDirectories(Paths.get("reports"));
            String filename = "reports/game_report_" + dateStr + ".txt";
            FileWriter writer = new FileWriter(filename);

            writer.write("NBA DAILY GAME REPORT - " + dateStr + "\n");
            writer.write("═".repeat(60) + "\n\n");
            writer.write("No games scheduled for this date.\n");
            writer.write("This could be an off-day, off-season, or休息 period.\n\n");
            writer.write("Report generated: " + java.time.LocalDateTime.now() + "\n");

            writer.close();
            System.out.println("📁 No-games report saved to: " + filename + "\n");

            updateTrackingLog(dateStr, 0);

        } catch (IOException e) {
            System.out.println("Error writing no-games report: " + e.getMessage());
        }
    }

    private void updateTrackingLog(String dateStr, int gameCount) {
        try {
            Files.createDirectories(Paths.get("reports"));
            FileWriter log = new FileWriter("reports/tracking_log.csv", true);

            // Check if file is empty (new file)
            boolean isNewFile = !Files.exists(Paths.get("reports/tracking_log.csv")) ||
                    Files.size(Paths.get("reports/tracking_log.csv")) == 0;

            if (isNewFile) {
                log.write("Date,Games_Played,Timestamp\n");
            }

            log.write(String.format("%s,%d,%s\n",
                    dateStr,
                    gameCount,
                    java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
            ));

            log.close();

        } catch (IOException e) {
            System.out.println("Error updating tracking log: " + e.getMessage());
        }
    }

    private String center(String text, int width) {
        int padding = (width - text.length()) / 2;
        return " ".repeat(Math.max(0, padding)) + text + " ".repeat(Math.max(0, width - text.length() - padding));
    }
}
